apiVersion: v1
kind : Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector: 
    app: tomcat-app
  ports:
    - name: tomcat-port
      protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 32000
